@Api_HostAddress = http://localhost:5122
@Functions_HostAddress = http://localhost:7071

###

GET {{Api_HostAddress}}/getvalue HTTP/1.1

###

GET {{Api_HostAddress}}/delay/50000000 HTTP/1.1

###

GET {{Functions_HostAddress}}/api/httptrekker HTTP/1.1

###

GET {{Functions_HostAddress}}/api/Health HTTP/1.1

###

GET https://tds-rdw-function.azurewebsites.net/api/Health

###

GET https://tds-rdw-function.azurewebsites.net/api/HttpTrekker

###
