trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

variables:
  project: "src/Function/Function.csproj"
  configuration: "Release"
  artifactName: "Function"
  azureSubscription: "azure-dw"

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - checkout: self

          - task: UseDotNet@2
            inputs:
              packageType: "sdk"
              version: "8.0.x"
              installationPath: $(Agent.ToolsDirectory)/dotnet

          - task: DotNetCoreCLI@2
            displayName: restore
            inputs:
              command: "restore"
              projects: "$(project)"
              feedsToUse: config
              nugetConfigPath: nuget.config

          - task: DotNetCoreCLI@2
            displayName: build
            inputs:
              command: "build"
              projects: "$(project)"
              arguments: "--no-restore -c $(configuration)"

          - task: DotNetCoreCLI@2
            displayName: publish project
            inputs:
              command: "publish"
              projects: $(project)
              zipAfterPublish: true
              publishWebProjects: false
              arguments: "-c $(configuration) -o $(Build.ArtifactStagingDirectory)"

          - task: PublishBuildArtifacts@1
            displayName: publish artifact
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "$(artifactName)"
              publishLocation: "Container"

  - stage: Deploy
    dependsOn: Build
    jobs:
      - deployment: Deploy
        environment: "tds-rdw-function"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: AzureFunctionApp@1
                  inputs:
                    azureSubscription: $(azureSubscription)
                    appType: "functionApp"
                    appName: "tds-rdw-function"
                    package: $(Pipeline.Workspace)/Function/Function.zip
                    deploymentMethod: "auto"
                    runtimeStack: "DOTNET-ISOLATED|8.0"
